spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081/
          predicates:
            - Path=/customer/**
          filters:
        - id: r2
          uri: http://localhost:8082/
          predicates:
            - Path=/account/**
          filters:
    discovery:
      enabled: true
  application:
    name: gateway-service

server:
  port: 8888







